create table if not exists extensions
(
    name    varchar(255) not null,
    data    bytea,
    version bigint,
    primary key (name)
);

create table if not exists users (
    id varchar(255) not null,
    display_name varchar(255) null,
    avatar varchar(255) null,
    bio varchar(255) null,
    email varchar(255) not null,
    email_verified boolean default false not null,
    phone varchar(255) null,
    encoded_password varchar(255) null,
    two_factor_auth_enabled boolean default false not null,
    totp_encrypted_secret varchar(255) null,
    disabled boolean default false not null,
    finalizers json null,
    annotations json null,
    created_by varchar(255) not null,
    last_modified_by varchar(255) not null,
    deleted_date timestamp with time zone null,
    created_date timestamp with time zone default current_timestamp not null,
    last_modified_date timestamp with time zone default current_timestamp not null,
    version bigint default 0 not null,

    primary key (id)
);

create index if not exists idx_email on users (email);
create index if not exists idx_phone on users (phone);

create table if not exists labels (
    id bigint generated by default as identity not null,
    entity_type varchar(255) not null,
    entity_id varchar(255) not null,
    label_name varchar(255) not null,
    label_value varchar(1023) not null,

    primary key (id),
    UNIQUE (entity_type, entity_id, label_name)
);

create index if not exists idx_entity on labels (entity_type, entity_id);
