name: Halo CI

on:
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - main
      - release-*
    paths:
      - "**"
      - "!**.md"
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  check:
    runs-on: ubuntu-latest
    # Default steps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            console:
              - 'console/**'
      - name: Check code style
        run: ./gradlew check -x test
      - name: Setup console environment
        if: steps.changes.outputs.console == 'true'
        uses: halo-sigs/actions/admin-env-setup@main
      - name: Check console
        if: steps.changes.outputs.console == 'true'
        run: |
          make -C console lint