name: Halo CI

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  halo-ci:
    name: Halo CI
    runs-on: ubuntu-latest
    # Default steps
    defaults:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name Cache Gradle wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
    steps:
      - name: Check And Test
        run: ./gradlew check

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build for unstable version
        run:
      - name: Docker build for stable version
        run: