name: Halo Build and Deploy

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Default steps
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Check And Test
        run: ./gradlew check

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Get Name of Artifact
        id: get_artifact
        run: |
          ARTIFACT_PATHNAME=$(ls build/libs/*.jar | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
          echo '::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}'
          echo '::set-env name=ARTIFACT_PATHNAME::${ARTIFACT_PATHNAME}'

      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARTIFACT_PATHNAME }}
          asset_name: ${{ env.ARTIFACT_NAME }}
          asset_content_type: application/java-archive

      - name: Docker build for unstable version
        run: docker info

      - name: Docker build for stable version
        run: docker info